---
- name: Gather configuration data
  hosts: localhost
  connection: local

  collections:
    - dellemc.powermax

  vars_files:
    - vars/credsvault.yml

  tasks:
  - name: Get a list of arrays (serial_no.)
    dellemc_powermax_gatherfacts:
        unispherehost: "{{ dell.unispherehost }}"
        universion: "{{ dell.universion }}"
        verifycert: "{{ dell.verifycert }}"
        user: "{{ dell.user }}"
        password: "{{ dell.password }}"
    register: arrays
            
  - name: Display the data that was just gathered
    debug:
            var: arrays
            verbosity: 1

  - name: Pull all available facts
    dellemc_powermax_gatherfacts:
        unispherehost: "{{ dell.unispherehost }}"
        universion: "{{ dell.universion }}"
        verifycert: "{{ dell.verifycert }}"
        user: "{{ dell.user }}"
        password: "{{ dell.password }}"        
        serial_no: "{{ item }}" # maps to an array (avail if you run the module without it)
        gather_subset: [ vol, srp, sg, pg, host, hg, port, mv ]
    loop: "{{ arrays.Arrays }}"
    register: results

  - name: Ensure a directory exists to store a fact report inside
    file:
            dest: reporting/
            state: directory

  - name: Create a local JSON file with current fact statistics
    copy:
            dest: "reporting/{{ ansible_date_time.date }}-powermax_facts.json"
            content: "{{ results|to_json }}"

