---
 - name: Install EPEL libraries in YUM
   hosts: planetexpress
   become: yes # run entire playbook with sudo

   tasks:
    - name: "Install epel-release"
      yum:
        name: epel-release
        state: present
      when: ansible_distribution == "CentOS"

    - name: "Update yum repos and Install package X"
      yum:
        update_cache: True
        name:
            - fail2ban
            - moon-buggy
        state: latest
      when: ansible_distribution == "CentOS"

