---
- name: Playbook - Install figlet
  hosts: pete
  gather_facts: yes   # default is yes

  tasks:
  - name: using apt to remove figlet
    apt:
        name: figlet
        state: absent
    become: yes

